MODEL:
  architecture:  "STMamba"
  shape_pattern: "NTHWC"
  img_res: 256
  max_seq_len: 8
  num_channels: 4 
  num_classes: 2
  dropout: 0.
  infer_res: 256
  model_path: 'Your_model_path'

DATASETS:
  train:
    dataset: "Nigeria"
    label_map:
    max_seq_len: 8
    batch_size: 4
    extra_data:
    num_workers: 1

  eval:
    dataset: "Nigeria"
    label_map:
    max_seq_len: 8
    batch_size: 4
    extra_data:
    num_workers: 1

  test:
    csv_path: 'Your_path/csv/seg_val.csv'
    base_dir: 'Your_path/pkl'
    batch_size: 1
    num_workers: 1
    save_path: 'Your_save_path'
    save_path_prob: 'Your_save_path'

SOLVER:
  num_epochs: 120
  num_warmup_epochs: 10
  steps: (0, 80000)
  loss_function:  TemporalCrossEntropyLoss
  class_weights: {'0': 1, '1': 5}
  ignore: 255
  temporal_weight: 0.1
  lr_scheduler: 'cosine'
  lr_base: 1e-4
  lr_min: 5e-6
  lr_start: 1e-8
  num_cycles: 1
  reset_lr: True   # resets lr to base value when loading pretrained model
  weight_decay: 0.01
